#!/usr/bin/env sh


for f in \
	.msmtprc \
	.Xdefaults \
	.xprofile \
	.xsession \
	.termcap \
	.tmux.conf \
	.mailcap \
	.offlineimaprc \
	.mutt \
	.vim \
	.vimrc \
	.gvimrc 
do

	rm -rf ~/${f}
	ln -s ${PWD}/${f} ~/${f}

done

