#!/usr/bin/env sh


for f in \
	.bashrc \
	.bash_profile \
	.gnupg \
	.ssh \
	.mayu \
	.Xmodmap \
	.msmtprc \
	.Xdefaults \
	.xprofile \
	.xsession \
	.termcap \
	.tmux.conf \
	.mailcap \
	.offlineimaprc \
	.mutt \
	.vim \
	.vimrc \
	.gvimrc 
do

	rm -rf ~/${f}
	ln -s ${PWD}/${f} ~/${f}

done

