#!/bin/sh

ag -s --ruby --haml --js --coffee --nogroup 'binding.pry|debugger|debug.*code' \
	--ignore vendor \
	--ignore lib/extentions/yajl_json.rb \
	--ignore delivery_test/delivery_support/request.rb \
	--ignore config/initializers/backtrace_silencers.rb

exit 0
