#!/bin/sh

# commit前にチェックするhook

if [ -z "$WIP" ] ; then

  # debug codeが残ってないかチェック。
  ag -s --ruby --haml --js --coffee --nogroup 'console.log|binding.pry|debugger|debug.*code' \
    --ignore vendor \
    --ignore config/initializers/backtrace_silencers.rb
  if [ $? -eq 0 ]; then
    exit 1
  fi

  # rubocop
  git diff --cached --name-only --diff-filter=AM | grep '\.rb$' | grep -v '^db/.*' | xargs bundle exec rubocop

fi

exit $?
