[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tyru/current-func-info.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp-all': {
  \        'configurationSources': ['flake8'],
  \        'plugins': {
  \          'pylsp_mypy': { 'enabled': 1 }
  \        }
  \      }
  \    }
  \  }
  \}
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = 'benmills/vimux'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
